# Generated by Django 4.0.4 on 2022-06-09 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID1', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personnes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=100)),
                ('nom_prenom', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('mot_de_passe', models.IntegerField()),
                ('ID1', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('categorie', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('ID1', models.CharField(max_length=100)),
                ('realisateur', models.CharField(max_length=100)),
                ('annee_de_sortie', models.DateField(blank=True, null=True)),
                ('affiche', models.URLField(null=True)),
                ('categorie', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaires',
            fields=[
                ('film', models.CharField(max_length=100)),
                ('personnes', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('note', models.CharField(max_length=100)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('categorie', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID1', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('age', models.DateField(blank=True, null=True)),
                ('photos', models.URLField(null=True)),
                ('categorie', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.categorie')),
            ],
        ),
    ]
